# _config.yml
title: Noxus' Hub
email: thisisnoxus@gmail.com
description: A portfolio showcasing my passions and projects
baseurl: ""
url: "https://gmanthenoxus.github.io"
github_username: gmanthenoxus

# Build settings
markdown: kramdown
theme: null
plugins:
  - jekyll-feed

# Add this to your _config.yml if not already there
collections:
  hobbies:
    output: true
    permalink: /hobbies/:name/
  projects:
    output: true
    permalink: /builds/:path/

# Make sure you have this defaults section
defaults:
  - scope:
      path: ""
      type: "hobbies"
    values:
      layout: "hobby"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/